version: "3"
services:
  mongo-container:
    image: mongo:latest
    container_name: mongo-zvas
    environment:
        - MONGO_INITDB_DATBASE=eshop-database
        - MONGO_INITDB_ROOT_USERNAME=local
        - MONGO_INITDB_ROOT_PASSWORD=localhost
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo-data:/data/db
    command: mongod
volumes:
  mongo-data:
    driver: local
